### PR TITLE
Update youtubeDiscordRelay.py

### PR DESCRIPTION
**Pull request by RViper80**
Discord made some changes to their API:
    servers became guilds,
    client.send_message(channel, message) became channel.send(message)

Also changed the Discord->Youtube chat to get the Discord nickname for that channel instead of their account registered name.

### CODE REVIEW

**Comment by popcorn9499** [comment]
Thank you this is much appreciated. I just hadnt gotten around to this myself. Thank you so much!

**Comment by RViper80** [comment]
No problem, this bot seems to work well.  I just updated it to use for myself and figured I'd toss what I did here :)

**Comment by popcorn9499** [comment]
only thing idk if you checked I thought it worked differently but I would have to run it to be sure. Thats how `message.author.display_name` works if the display_name isnt set. we may need a check to see if its not empty. I just can't quite remember because its been awhile since i worked with that part of discordpy

**Comment by popcorn9499** [comment]
nvm i was thinking if its a private message. Ignore that bit about message.author.display_name. It should work

**Comment by RViper80** [comment]
I just tried checking that now, but it seems the script is overloading the youtube API daily quotas, might have to slow down the checking rate.

Edit:  Looking up the data, it seems that Youtube allowed 50M requests/day prior to 5/13/2016, then reduced it to 1M after that, and finally it's now at 10,000 Queries per day as of 1/11/2019.  I think the 'ListChat' function may need updating, but I can't work on that today as that meager 10k queries seems to be used up in about two hours from this script as it is now.

**Comment by popcorn9499** [comment]
let me check the polling rates
just a moment i can possibly fix that

**Comment by popcorn9499** [comment]
you said 2 hours as of right now right? well were u recieving messages too just checking that changes stuff too.
I was looking into parsing the actual physical webpage directly instead of going through the api cuz 10k queries isnt enough.

the api u have to pull to get messages there isnt a subscribe event method or anything sadly so right now im polling every 5 seconds but even that isnt gonna help much increasing it to 10 or 30. what i might want to do is implement a sorta gradual rate limit thing where it say keeps track of the last x messages in the last x minutes and if it hasnt recieved a new message in 2 minutes then it throws up a extra delay or something. that may work as well..

however parsing the webpage directly may be a faster and easier way to do it sadly

**Comment by popcorn9499** [comment]
Myself I think i either have 50m requests/day or 1M/day and i leave the app running all day 24/7

**Comment by popcorn9499** [comment]
I had fixed this in a different bot i wrote doing basically the same thing but for discord youtube and irc/twitch. However i appear to ahve broken it. I was doing requests/s of 0.099/s but now it jumped to 0.243/s

however in the last day for me leaving it on 24/7 it was 21,209 requests in a full day that is including a live stream.


The requests amounts will vary for more messages getting received or sent

**Comment by popcorn9499** [comment]
btw what part of the listchat function needs changing? it should all still work nothing should be changed really in it past what you changed with the  channel stuff.

I really need to just rewrite this entire project however cuz honestly its kinda messy. guess thats what happens when you come right out of a gr 11 computer science course and write a project then sorta not really touch it because it just worked.

**Comment by RViper80** [comment]
Nope, that 10k requests was just leaving it running, as far as I know no chat messages were sent either way during that time.

I was just guessing that maybe the listchat function could be improved to request less data from the YouTube API, which would help the quota limit.  But as I really haven't worked with that API at all, I have no real clue on if it could be improved or not.

Edit:  I'm basing the fact that it only lasted about 2-2.5 hours on the traffic graph on the APIs & Services google page.  Traffic is low (0.2/sec) until 2AM local time (quota reset time), at which point it jumps to about 0.4/sec until around 4:30, at which point its back down to 0.2/sec.

Edit2:  Figuring that out, 2.5 hours would be about 3600 requests, but according to their api, a snippet lookup seems to be a minimum of 3 points, which brings it up to 10800, and over the limit.  Even 0.09/sec would only get through half the day on that 10k limit, and that's not even with any chat messages going.  That's an insanely small limit they went to.

**Comment by popcorn9499** [comment]
honestly the limit almost makes using the api for this project nearly impossible. ive been told u can request a higher limit. i will change a few things the only ways i can think of is rate limiting chat so it goes into a mock slow mode type deal with no messages.


I didnt think they actually had details on how this works.

The minimum number to pull from the youtube live chat list api is 200 results i think

**Comment by popcorn9499** [comment]
this is the commit that may improve that limit likely not by much im gonna do some more work potentially on this but i dont see how i could honestly fix this entirely. https://github.com/popcorn9499/Youtube-Discord-Relay-Bot/commit/9e480c5ee0493591fb96bec94829009e8fc89c54

**Comment by RViper80** [comment]
I do like that idea of making it slower if there's no messages recieved, that would help a lot also.

I changed the refresh time from five seconds to one minute on my local copy, in theory that should put me at a little over 8k quota points with no messages for 24 hours.  Won't be able to test that for another 11 hours though.

**Comment by popcorn9499** [comment]
i think honestly potentially the best but most troublesome solution would be to parse the page directly. googles api limits atm make that a viable option tbh.

**Pull request merged**
